### ISSUE TITLE
Do you mind if I create better instructions?

### ISSUE THREAD

**Issue by Th3OnlyN00b** [charlescao460/iSkipper-Software#2]
So I figured out how to install everything and finally got it set up but it took a while because it was my first maven setup so I was wondering if I could update the README with better instructions on how to set up Maven and compile the projects. No offence to your instructions, they're just a little short for people for whom this is their first maven project.

**Comment by charlescao460** [comment]
No problem!
Just create a pull request and I'll merge your fork into this repo.
And please don't hesitate to create a PR if you've done any improvement:)

For your convenience to develop, this repo actually contains Eclipse `.project` files [here](https://github.com/charlescao460/iSkipper-Software/blob/master/Software/iSkipper-JavaFX/.project)
and [here](https://github.com/charlescao460/iSkipper-Software/blob/master/Software/Java/iSkipper/.project). Therefore the entire `iSkipper-JavaFX` and `iSkipper-Software` folders can be imported into Eclipse as Maven projects. With `pom.xml`, the similar importing operation could also be done in IntelliJ IDEA. 

By the way, as mentioned in #1 , the Arduino Sketch probably has some problems. I am still working on it to re-write the entire sketch. So please ask me if you've met any strange problem when using this repo.

Thank you for your contribution!

**Comment by Th3OnlyN00b** [comment]
I already figured out how to import them as Mavens, that was part of my confusion during installation haha. I'll certainly take a look, yeah!

**Comment by charlescao460** [comment]
#3 The README has been updated.
